k8sgpt-ai/k8sgpt-operator

.github/workflows/release.yaml
=> feat: adding helm chart release operations

.github/workflows/release.yaml
=> chore: fixing missing release trigger

README.md, chart/operator/values.yaml
=> chore: updated example readme

.github/workflows/test.yaml, chart/operator/Chart.yaml, chart/operator/values.yaml
* fixes issues when the chart changes and the chart version stays the same (chart version is incremented with release please)
=> fix: disable version checking for helm charts

chart/operator/README.md
This PR closes https://github.com/k8sgpt-ai/k8sgpt-operator/issues/52
Added new entry in helm chart readme.md for service monitor additional labels that were added recently.
=> chore: update helm readme with servicemonitor labels

README.md
Closes # 
Tiny PR to  fix localai's backend name in README's example.
=> docs: fix localai's backend name

controllers/k8sgpt_controller.go
Closes # 
Registers the rest of our custom Prometheus metrics
=> feat: register all the custom prom metrics

README.md
Closes https://github.com/k8sgpt-ai/k8sgpt-operator/issues/69
Fix example in readme
=> Fix Readme example for k8sgpt-local-ai 

README.md
=> chore: updated readme url

pkg/client/client.go
Closes # 
Adds backend config name to analysis request so operator can work with other ai providers besides openai
=> fix: Add missing backend from analysis request.

chart/operator/templates/grafana-k8sgpt-dashboard.yaml, chart/operator/values.yaml
Reverts k8sgpt-ai/k8sgpt-operator#105
=> Revert "Customize Grafana annotation and label"

chart/operator/templates/grafana-k8sgpt-dashboard.yaml, chart/operator/values.yaml
=> feat: parameterise grafana's annotations and labels

pkg/resources/k8sgpt.go, pkg/utils/utils.go
Closes #92  
This PR adds controller references to existing ownerRef resources
=> feat: add controller reference to resources

chart/operator/templates/k8sgpt-crd.yaml
Closes # 
Add filters in chart's CRDs, atm users can't leverage filters when installing the operator via HELM
=> chore: add filters to operator helm chart's crd

README.md
Closes #141 #132 
Fix LocalAI instructions in README.
=> docs: update LocalAI instructions in README

controllers/k8sgpt_controller.go, go.mod, go.sum, main.go, pkg/client/client.go
=> feat: refactored plus fixed client

go.mod, go.sum
=> chore: updated schema for integrations support

chart/operator/templates/k8sgpt-crd.yaml
=> chore: fix missing integration

README.md
Image is missing the "s" in k8s
Closes # 
- [X ] My pull request adheres to the code style of this project
- [ X] My code requires changes to the documentation
- [ X] I have updated the documentation as required
- [X ] All the tests have passed
=> Correct k8sgpt image name

CONTRIBUTING.md
Small PR to document the local development of the operator
Closes #
=> docs: local mode

chart/operator/templates/k8sgpt-crd.yaml
Closes #344 
add kubeconfig in helm template
=> fix: add kubeconfig field in helm chart crd template

README.md
Typo fix for the Amazon Bedrock documentation in README.
=> docs: fix Amazon Bedrock instructions in README

pkg/resources/results.go
=> bug: fixing missing details

pkg/resources/results.go
=> chore: small update to fix linter

api/v1alpha1/result_types.go, chart/operator/templates/result-crd.yaml, config/crd/bases/core.k8sgpt.ai_results.yaml
Closes # 
It would be convenient to see the `age` of `result`.
=> Print the age of result

.github/workflows/test.yaml, Makefile, api/v1alpha1/k8sgpt_testing.go, config/samples/valid_k8sgpt.yaml, controllers/analysis_step.go, controllers/configure_step.go, controllers/finalizer_step.go, controllers/init_step.go, controllers/k8sgpt_controller.go, controllers/k8sgpt_controller_test.go, controllers/preAnalysis_step.go, controllers/resultStatus_step.go, controllers/suite_test.go, main.go, pkg/metrics/metrics.go
Closes # 
This PR introduces a new approach to breaking down the reconciliation loop, which has become quite complex and difficult to read. By applying this [pattern](https://refactoring.guru/design-patterns/chain-of-responsibility/go/example), we could split each step of the reconciliation loop into several distinct "steps." This would not only improve code readability but also allow us to independently test each step by mocking its inputs and outputs.
Simple integration tests have also been added, but they will need to be strengthened in the future. A testing phase should be conducted before merging this PR.
=> feat: rework controllers logic & add some simple tests

README.md, api/v1alpha1/k8sgpt_types.go, api/v1alpha1/k8sgpt_types_test.go, chart/operator/templates/k8sgpt-crd.yaml, config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml, controllers/configure_step.go
Closes #540 
Change default backOff enabled value to true.
Add backOff on README example yaml.
Also, I will add backOff in document repo.
=> fix: change backOff default enabled value to false

config/manager/kustomization.yaml, pkg/resources/k8sgpt.go
Closes # 
- [xx ] I have updated the documentation as required
=> feat: fixes breaking change with missing service account

chart/operator/templates/k8sgpt-crd.yaml
=> feat: updated k8sgpt crd

config/samples/caching_example.yaml
=> feat: fix secret caching

config/samples/caching_example.yaml, pkg/client/analysis.go, pkg/common/types.go
=> fix: spelling fix

chart/operator/values.yaml
=> chore: updated to support rbac-proxy

Makefile, controllers/analysis_step.go, pkg/resources/results.go
=> feat: fixes missing data by type

README.md, api/v1alpha1/k8sgpt_types.go, api/v1alpha1/k8sgpt_types_test.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml, config/samples/custom_analzyer_example.yaml, pkg/resources/k8sgpt.go
Closes https://github.com/k8sgpt-ai/k8sgpt/issues/1277
Add Resource Configuration Options to K8sGPT CRD, And  Configure the k8sgpt deployment resource if required
=> feat: Add Resource Configuration Options to K8sGPT CRD

README.md
Closes # 
- [] All the tests have passed
=> Bug Fix: Fixing Amazon Bedrock example

AUTO_REMEDIATION.md, api/v1alpha1/k8sgpt_types.go, chart/operator/templates/mutation-crd.yaml, config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml, config/samples/autoremediation/valid_k8sgpt_remediation_sample.yaml, internal/controller/mutation/mutation_controller.go
=> feat: renamed to similarity requirement for scoring

README.md, config/samples/valid_k8sgpt.yaml
=> feat: auto remediation title

chart/operator/templates/k8sgpt-crd.yaml, chart/operator/templates/mutation-crd.yaml, config/samples/valid_k8sgpt.yaml
=> feat: updated helm chart

chart/operator/README.md, chart/operator/templates/deployment.yaml
Closes # [](https://github.com/k8sgpt-ai/k8sgpt-operator/issues/619)
Update the helm chart to allow user define additional labels for deployment
=> Add user defined labels to the deployment

README.md, config/samples/autoremediation/valid_k8sgpt_remediation_sample.yaml, internal/controller/k8sgpt/analysis_step.go
=> chore: small debug improvements

README.md, config/samples/autoremediation/valid_k8sgpt_remediation_sample.yaml, config/samples/valid_k8sgpt.yaml, internal/controller/k8sgpt/analysis_step.go
=> chore: readme update

Makefile, config/samples/autoremediation/valid_k8sgpt_remediation_with_interplex.yaml
=> chore: local example interplex

Makefile, config/samples/autoremediation/valid_k8sgpt_remediation_with_interplex.yaml, demo.sh
Closes # 
-[x ] My pull request adheres to the code style of this project
=> chore: demo-sh

demo.sh
=> chore: updated demo.sh

pkg/resources/k8sgpt.go
Revert accidental VolumeMount removal introduced by #634
=> Revert accidental VolumeMount removal introduced by #634

chart/operator/templates/k8sgpt-crd.yaml, config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
=> feat: irsa missing from crd chart

README.md, api/v1alpha1/k8sgpt_types.go, chart/operator/templates/k8sgpt-crd.yaml, config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml, config/samples/exhaustive_sample.yaml, pkg/resources/k8sgpt.go
=> feat: Add imagePullPolicy for K8SGPT instances

api/v1alpha1/k8sgpt_types.go, chart/operator/templates/k8sgpt-crd.yaml, config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
Closes # 
https://github.com/k8sgpt-ai/k8sgpt/pull/1228#issuecomment-2796191519
=> feat: add 'customrest' to backend options in CRD

internal/controller/k8sgpt/preAnalysis_step.go
=> chore: fixing issue with non-auto remediation loop failure

pkg/resources/k8sgpt.go
=> feat: adding new analyzer permissions

pkg/resources/k8sgpt.go
=> chore: fixed uninitialised annotations

chart/operator/templates/deployment.yaml, chart/operator/values.yaml
=> feat: adding optional annotations to the controller manager

internal/controller/k8sgpt/k8sgpt_controller.go
=> feat: displaying the requeue time

README.md
=> chore: added analysis interval

cmd/main.go, internal/controller/mutation/mutation_controller.go, internal/controller/mutation/mutation_controller_test.go, internal/controller/shared/client.go
=> feat: fixing the reconciliation mechanism

pkg/resources/k8sgpt.go
Closes #669 
Service Sync only update necessary fields,  to avoid conflicts,in issue #669
=> fix: service only sync necessary fields to avoid conflicts

config/samples/exhaustive_sample.yaml
Closes # 
This pull request improves the exhaustive_sample.yaml file to make it more accurate, comprehensive, and user-friendly.
Ensuring completeness: Verified that all available fields from the K8sGPT CRD are present in the sample.
=> docs: Improve and correct exhaustive_sample.yaml
