k8sgpt-ai/k8sgpt-operator

- LICENSE
ts PR will contribute to closing https://github.com/k8sgpt-ai/k8sgpt/issues/341 once all checkboxes are ticked for all repos in the org.
The current state of the license is not formatted properly. This matters as GitHub and other tools don't pick it up properly as being an Apache2 license. To be consistent I have updated this to be the proper version that is consistent with all of our repos. I have also included the copyright section which is important.
> chore: update format of Apache2 license

- renovate.json
* Ignores old client-go packages, as renovate tries to downgrade to v11
> fix: ignore old client go packages in renovate

- chart/operator/templates/controller-manager-metrics-monitor.yaml
- chart/operator/values.yaml
Closes #[364](https://github.com/k8sgpt-ai/k8sgpt/issues/364)
This PR is to add the ability to add your own labels to the service monitor. In my case I use the Prometheus operator therefore I need to add an additional label so it references my prometheus release which is:
```yaml
labels:
release: kube-prometheus-stack
```
For the reviewer testing this, you can run these tests.
Scenario 1: Run helm chart with service monitor enabled is false
in the values.yaml, the serviceMonitor enabled is false as follows:
```yaml
serviceMonitor:
enabled: false
```
Scenario 2: Run helm chart without the additional labels
in the values.yaml, only use the serviceMonitor enable is true as follows:
```yaml
serviceMonitor:
enabled: true
```
Scenario 3: Run helm chart with the additional labels
in the …
> feat: add additionalLabels to serviceMonitor

- api/v1alpha1/k8sgpt_types.go
- chart/operator/Chart.yaml
- chart/operator/templates/k8sgpt-crd.yaml
- config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
- pkg/resources/k8sgpt.go
Closes # 
Adding azureopenai backend and introduce kubebuilder markers to assign default values for `model=gpt-3.5-turbo` and `backend=openai`  
I've also added an evaluation on the backend accepted names to help users define their desired backend name
There is a reconcile error if a user tries to specify `engine` without having azureopenai as their backend.
example:
```Finished Reconciling K8sGPT with error: Engine is supported only by azureopenai provider.
2023-05-05T20:29:08+03:00	ERROR	Reconciler error	{"controller": "k8sgpt", "controllerGroup": "core.k8sgpt.ai", "controllerKind": "K8sGPT", "K8sGPT": {"name":"k8sgpt-sample","namespace":"kube-system"}, "namespace": "kube-system", "name": "k8sgpt-sample", "reconcileID": "5a08a085-610b-44f6-ada8-19f052aad6b3", "error": "Engine is …
```
> feat: add azureopenai backend

- .gitignore
- controllers/k8sgpt_controller.go
- pkg/resources/k8sgpt.go
- This fixes issues with DNS propagation making the service IP for the k8sgpt-deployment inaccessible with some CNI
- This fixes the bug where reconciliation updates of Results do not work properly
> feat: feat/direct pod ip

- controllers/k8sgpt_controller.go
> fix: stagnent results

- chart/operator/templates/grafana-k8sgpt-dashboard.yaml
- chart/operator/values.yaml
Closes # 
Grafana sidecar load dashboards using an annotation and a label. These annotation and label are customizable.
This PR add this feature.
> Customize Grafana annotation and label

- README.md
- chart/operator/README.md
- chart/operator/templates/k8sgpt-crd.yaml
- chart/operator/templates/result-crd.yaml
Closes # 
Adding the Sink CRD updates to helm chart and update README file
> chore: add crds to helm and update README file.

- pkg/resources/results.go
Closes # 
Small PR to fix the way we decide to update the Result CR,
we compare the number of errors that are returned from K8sGPT -- `Spec.Details` may change although its context remains the same
> fix: compare the number of errors to update Results

- chart/operator/templates/grafana-k8sgpt-dashboard.yaml
- chart/operator/values.yaml
Closes #138 
The `namespace` field has been added to the `grafanaDashboard` section of the `values.yaml` file. This allows the Grafana dashboard to be deployed to a specific namespace, which improves organization and separation of concerns.
> feat(operator): add namespace to grafanaDashboard

- pkg/resources/k8sgpt.go
Adding `OwnerReferences` field to `Service` and `ServiceAccount` to  avoid being kept when uninstall k8sgpt. Keep the same behavior with `deployment`.
> feat: add owner reference

- pkg/sinks/slack.go
Closes # 
In order to avoid having multiple slack channels to forward messages from k8sgpt operator we add a prefix to our slack messages, so it's more transparent which k8sgpt deployment is responsible for each analysis report.
e.g naming your K8sGPT CR with the name of your clusters you can track down easier where the problem is located and using a single pane of glass aka a single slack channel.
This was requested on slack and I think it adds value. Unfortunately is not yet feasible to discern the name of your K8s cluster from within  the cluster so there is no way to add it programmatically..
> feat: add K8sGPT Custom Resource name as a prefix to slack messages

- pkg/integrations/integrations.go
- pkg/resources/results.go
Closes #226  
Logging and not propagating errors when retrieving objects for backstage label support.
We shouldn't trigger a whole new reconciliation for backstage support errors
> chore: only log and stop propagating backstage errors

- chart/operator/templates/manager-rbac.yaml
Closes #248 #252  
This PR fixes the RBAC issues introduced in the 0.0.22 release.
Effectively K8s won't allow an SA to create cluster roles more permissive than its own cluster roles, 
so we match the permission which will be eventually set for the K8sgpt cluster role.
I will create a new feature request to lift and shift all the RBAC related resources to Helm chart templates which will be more clear to the user what roles will be created by K8sGPT operator whilst avoiding this matching pattern between the two cluster roles
> fix: operator's cluster role permissions to match k8sgpt

- pkg/resources/results.go
Closes #263
The following PR labels the `Result` objects with some additional labels, such as:
- `k8sgpts.k8sgpt.ai/name`, referring to the `k8sgpt` resource's Name
- `k8sgpts.k8sgpt.ai/namespace`, referring to the `k8sgpt` resource's namespace
- if specified, `k8sgpts.k8sgpt.ai/backend`, referring to the `k8sgpt` used AI driver
N.R.
> feat: results are labeled

- README.md
- api/v1alpha1/k8sgpt_types.go
- api/v1alpha1/k8sgpt_types_test.go
- chart/operator/templates/k8sgpt-crd.yaml
- config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
- controllers/k8sgpt_controller.go
- pkg/resources/k8sgpt.go
Closes #268   
- add image repository in k8sgpt crd.
- remove hardcoded image repository.
- controller reconcile repository not just version
> remove hardcoded k8sgpt image respository

- README.md
- api/v1alpha1/k8sgpt_types.go
- config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
- go.mod
- go.sum
Closes #276  
There was a typo in the kubebuilder marker regarding k8sgpt image name
I also updated README
> chore: update kube marker

- controllers/k8sgpt_controller.go
> feat: added llm metric analysis count

- README.md
- api/v1alpha1/k8sgpt_types.go
- chart/operator/templates/k8sgpt-crd.yaml
- config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
- pkg/sinks/mattermost.go
- pkg/sinks/sinkreporter.go
Closes #300
1. added mattermost sink
- support mattermost incoming webhook
2. added parameter on sink (K8sGPT API)
- `Channel` (Mattermost Optional Param)
- `Username`  (Mattermost Optional Param)
- `IconURL`  (Mattermost Optional Param)
- [Mattermost Docs](https://developers.mattermost.com/integrate/webhooks/incoming/)
1. Confirmed that no value is entered in the notification content when ai is set to `enable: false`.
(current Slack notifications may be notified with no value as well.)
Change to -> I tried to load error text when ai is enable: false.
3. E2E Test Contents
- test assets is [here](https://github.com/tozastation/k8sgpt-operator-contribute-asset/tree/main/issue-300/k8s)
- deploy mattermost server
- applying resources detected in k8sgpt 
- confirmation of incoming …
> feat: add mattermost sink

- controllers/k8sgpt_controller.go
- grafana/custom-metrics/custom-metrics-dashboard.json
- grafana/k8sgpt-overview.json
Closes #363  
add prometheus metric label to distinguish clusters.
i set label name as k8sgpt. and its value is `k8sgpt.metadata.name`. if there is more appropriate label name, please suggest.
example metric
```
k8sgpt_reconcile_error_count{k8sgpt="gangnam1"} 13
```
> fix: add prometheus metric label "k8sgpt"

- pkg/client/client.go
No idea if this works.  This is literally my first Go code (my "hello world" but IPv6 attempt).
Closes #369
Detect if a `ClusterIP` is IPv6 or IPv4.  Choose the appropriate string format based on Go documentation.
https://pkg.go.dev/net
> A literal IPv6 address in hostport must be enclosed in square brackets, as in "[::1]:80", "[::1%lo0]:80".
I've tested locally that it compiles with `make`.  I've not done any extra testing beyond that.  My development environment is Ubuntu 22.04.
I've successfully run `make test` from [my development environment](https://github.com/samrocketman/goenv).
```bash
$ go version
go version go1.21.6 linux/amd64
```
> Support for IPv6 clusters

- api/v1alpha1/k8sgpt_types.go
- chart/operator/templates/k8sgpt-crd.yaml
- config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml
This commit adds `gemini` to the list of supported AI backends.
Fixes: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/347
> [feature]: added gemini to supported AI backends

- README.md
There was a misplaced details block causing the Bedrock section not to function as expected.
> docs: syntax issue in README

- pkg/resources/results.go
Closes #447 
Also fix https://github.com/k8sgpt-ai/k8sgpt/issues/1116 and https://github.com/k8sgpt-ai/k8sgpt/issues/1107
`Result`'s namespace field was being filled in incorrectly: it was previously being populated with the namespace from config, which was replaced with the targetNamespace of `k8sgpt` in this [PR](https://github.com/k8sgpt-ai/k8sgpt-operator/pull/399). However, most users don't specify a targetNamespace and this field is nil, causing an error.
Here's the fix, and how it's working again after the fix.
> fix: rollback namespace bug

- README.md
After the https://github.com/k8sgpt-ai/k8sgpt-operator/pull/86, 
```
{
"apiVersion": "v1",
"items": [],
"kind": "List",
"metadata": {
"resourceVersion": "",
"selfLink": ""
}
}
``` 
There is no result in the default namespace.
And in the `k8sgpt-operator-system` namespace, it can work, like:
```
NAME              KIND      BACKEND   AGE
defaultdao2048    Service   openai    61m
defaultvllmlora   Service   openai    61m
```
Closes #
> chore: fix missing namespace in README

- pkg/resources/k8sgpt.go
I propose that the hardcoded check in the operator to set the `K8SGPT_PROXY_ENDPOINT` environment variable gets removed, in other to allow it to be set in any backend. This gives flexibility and allows k8sgpt-operator users that are behind proxies to setup this variable to any backend (e.g. localai). 
In my use case I have a remote Ollama backend and I need to access it through a proxy. K8SGPT allows Ollama to have a proxy endpoint defined, reference https://github.com/k8sgpt-ai/k8sgpt/blob/d1a29e400168053cb7357701995e30ffb8640efb/pkg/ai/ollama.go#L51
> Remove ProxyEndpoint hardcoded backend checks to allow usage of HTTP proxies in any backend

- api/v1alpha1/result_types.go
- chart/operator/templates/result-crd.yaml
- config/crd/bases/core.k8sgpt.ai_results.yaml
- pkg/resources/results.go
The Problem: The AI would generate slightly different wording for the same issue each time, causing the operator to think the result "changed" and send duplicate notifications every 30 seconds.
We now hash the meaningful parts of each result (kind, name, parent object, error texts) and ignore the AI-generated details that naturally vary. If the hash is the same, we know it's the same issue → mark as "historical" → no notification sent.
> feat: sneaky little bug fix
